# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"            # workflows are under .github/workflows
    schedule:
      interval: "weekly"
