name: Update SECURITY.md Supported Versions

on:
  schedule:
    - cron: "17 3 * * *"   # nightly UTC
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml packaging

      - name: Update SECURITY.md
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/update_security_versions.py

      - name: Create Pull Request
        if: always()
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(security): refresh Supported Versions table"
          title: "chore(security): refresh Supported Versions table"
          body: "Automated refresh of Supported Versions from tags/releases."
          branch: ci/update-security-versions
          delete-branch: true
